# Generated by Django 4.2 on 2024-10-03 13:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('country_title', models.CharField(default='', max_length=50)),
                ('slug', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('region_title', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(default='', max_length=100)),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='main.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('city_title', models.CharField(default='', max_length=100)),
                ('city_image', models.URLField(default='', max_length=255)),
                ('slug', models.CharField(default='', max_length=100)),
                ('region', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='main.region')),
            ],
        ),
    ]
