# Generated by Django 4.2 on 2024-10-09 16:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionRubrics',
            fields=[
                ('rubric_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=150)),
                ('slug', models.SlugField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('profession_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('slug', models.CharField(default='', max_length=100)),
                ('rubric_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.professionrubrics')),
            ],
        ),
    ]
