# Generated by Django 4.2 on 2024-10-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_professionrubrics_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='rubric_id',
        ),
        migrations.AddField(
            model_name='profession',
            name='rubric_id',
            field=models.ManyToManyField(default='', to='main.professionrubrics'),
        ),
    ]
