# Generated by Django 4.2 on 2024-10-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_remove_jobseeker_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseeker',
            options={},
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='last_name',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
